package defaultpck;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ctsuser1' at '5/15/17 11:17 PM' with Gradle 2.14.1
 *
 * @author ctsuser1, @date 5/15/17 11:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
